/*
 * USART_config.h
 *
 *  Created on: Aug 5, 2023
 *      Author: larar
 */

#ifndef MCAL_USART_CONFIG_H_
#define MCAL_USART_CONFIG_H_

#define USART_MODE			ASYNCHRONOUS

#define USART_PARITY		USART_PARITY_EVEN

#define USART_STOP_BITS		USART_1_STOP_BITS

#define USART_BIT_SIZE		USART_8_BIT

#define USART_CLK_EDGE		USART_CLK_RISING

#define USART_SPEED			USART_SPEED_NORMAL

#define USART_BAUD_RATE		9600

#define F					8000000UL

#endif /* MCAL_USART_CONFIG_H_ */
